version: 2

jobs:
  build:
    working_directory: ~/island-troll-tribes

    docker:
      - image: circleci/openjdk:8-jdk-browsers

    steps:
      - checkout

      - run:
          name: Install Wurst
          command: |
            wget https://grill.wurstlang.org/hudson/job/WurstSetup/lastSuccessfulBuild/artifact/downloads/WurstSetup.jar -O ~/.wurst/WurstSetup.jar
            java -jar WurstSetup.jar install wurstscript

      - run:
          name: Update Dependencies
          command: |
            rm ~/.gitconfig
            java -jar ~/.wurst/WurstSetup.jar update

      - run:
          name: Test
          command: |
            rm _build/dependencies/wurstExtLibs.git/wurst/war3map.j
            java -jar $HOME/.wurst/wurstscript.jar $HOME/.wurst/common.j $HOME/.wurst/blizzard.j ./ -runcompiletimefunctions -runtests
